# Generated by Django 4.0.3 on 2023-02-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='categoria',
            field=models.CharField(choices=[('CLÁSSICOS', 'Clássicos'), ('FILOSOFIA', 'Filosofia'), ('CIÊNCIA', 'Ciência'), ('BIOGRAFIAS', 'Biografias'), ('FANTASIA', 'Fantasia'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror')], default='', max_length=100),
        ),
    ]
