# Generated by Django 4.0.3 on 2023-02-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_resenha_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='categoria',
            field=models.CharField(choices=[('Clássicos', 'CLÁSSICOS'), ('Filosofia', 'FILOSOFIA'), ('Ciência', 'CIÊNCIA'), ('Biografias', 'BIOGRAFIAS'), ('Fantasia', 'FANTASIA'), ('Romance', 'ROMANCE'), ('Terror', 'TERROR')], default='', max_length=100),
        ),
    ]
