# Generated by Django 4.0.3 on 2023-02-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_resenha_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
