# Generated by Django 4.0.3 on 2023-02-25 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_resenha_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
