# Generated by Django 4.0.3 on 2023-03-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_resenha_data_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
